### ISSUE TITLE
Is this the most recent version?

### ISSUE THREAD

**Issue by aeschylus** [mekarpeles/groovebox.org#1]

**Comment by mekarpeles** [comment]
Nope, pushing the latest version w/ APIs in 10 minutes -- finishing a v1 of
the "tracks" API so we can retrieve a list of tracks from a concert. Will
send an update when it's pushed.

There are 2 challenges:
1. Each concert item on Archive.org has several file-types (ogg, flac,
   mp3, sdn, etc), each having different metadata (like song duration in
   minutes v. seconds) and different titles across file-types (making it hard
   to parse a list). They need to be entity resolved and then their metadata
   made uniform.
2. There need to be 2 different API views for getting tracks
   1. Getting an ordered list of tracks (all of the same file-type) for
      a concert
   2. Getting a global list of tracks (song names) and the artists who
      perform them.

best wishes,
- mek

**Comment by mekarpeles** [comment]
Code up on master is the latest version. Will be using feature branches from now on.

**Comment by aeschylus** [comment]
Cool. I'd like to polish up the interface by tending to some
microinteractions (hover effects and activation feedback for album and song
links, list items, the player itself, etc.).
